name: '[AutoGen nuget] Publish all packages'

on:
   push:
     paths:
     - 'dotnet/src/**'
     - 'protos/**'
   workflow_dispatch:
 
permissions:
    id-token: write
    contents: read
jobs:
    init:
      runs-on: ubuntu-latest
      outputs:
        version_suffix: ${{ steps.set_version_suffix.outputs.VERSION_SUFFIX }}
        version_prefix: '0.0.1'
      steps:
        - name: Set version suffix
          id: set_version_suffix
          run: echo "VERSION_SUFFIX=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"
    build-test-packages:
      uses: ./.github/workflows/dotnet-build-test-packages.yml
      needs: init
      secrets: inherit
    publish-packages:
      name: Publish .NET packages
      runs-on: ubuntu-latest
      needs: build-test-packages
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - name: Publish package
          run: |
            cd dotnet/src/${{ inputs.path }}
            dotnet pack -o packages /p:PackageVersion=${{ inputs.version-prefix }}-alpha.${{ inputs.version-suffix }} 
            dotnet nuget push $GITHUB_WORKSPACE/dotnet/src/${{ inputs.path }}/packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}  --source https://api.nuget.org/v3/index.json
