name: "Git LFS Check"

on: pull_request
permissions: {}
jobs:
  lfs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: "Check Git LFS files for consistency, if you see error like 'pointer: unexpectedGitObject ... should have been a pointer but was not', please install Git LFS locally, remove the file and add it again to make sure it is tracked."
        run: |
          git lfs fsck
